fetch:
	wget http://lorempixel.com/600/400/sports/1
	mv 1 600-400-sports-1
	wget http://lorempixel.com/300/200/sports/1
	mv 1 300-200-sports-1

	wget http://lorempixel.com/400/600/food/1
	mv 1 400-600-food-1
	wget http://lorempixel.com/200/300/food/1
	mv 1 200-300-food-1

	wget http://lorempixel.com/600/400/nature/1
	mv 1 600-400-nature-1
	wget http://lorempixel.com/300/200/nature/1
	mv 1 300-200-nature-1

	wget http://lorempixel.com/400/600/people/1
	mv 1 400-600-people-1
	wget http://lorempixel.com/200/300/people/1
	mv 1 200-300-people-1

	wget http://lorempixel.com/600/400/business/1
	mv 1 600-400-business-1
	wget http://lorempixel.com/300/200/business/1
	mv 1 300-200-business-1

	wget http://lorempixel.com/600/400/technics/1
	mv 1 600-400-technics-1
	wget http://lorempixel.com/300/200/technics/1
	mv 1 300-200-technics-1
